sudo: required

language: node_js

node_js:
  - "8.5.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - "travis_phantomjs"

before_install:
  - cd wzk-demo
  - npm install -g bower grunt grunt-cli node-gyp
  - npm install
  - bower install

script: grunt build
